name: Convert Avro IDL to Avro Schema

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert-avro-idl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Install Avro Tools
      run: |
        wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.11.3/avro-tools-1.11.3.jar

    - name: Convert Avro IDL to Avro Schema
      run: |
        find . -name "*.avdl" -exec sh -c 'java -jar avro-tools-1.11.3.jar idl2schemata {} $(dirname {})' \;

    - name: Commit and push changes
      run: |        
        git config user.name 'Pedro Frederico'
        git config user.email 'pmgfrederico@gmail.com'
        git add .
        git commit -m 'Convert Avro IDL to Avro Schema'
        git push        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"